### ISSUE TITLE
Differences between Dolby Vision Media Profile and market implementations

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#18]
There are multiple Dolby Vision implementations in the market today which use custom NAL Units to convey dynamic metadata, rather than SMPTE 2094-10 SEI messages specified in ATSC 3.0 and proposed in WAVE. If we publish a DV media profile based on SEI messages, will the WAVE profile be out of step with the industry? And if so, how will that impact the relevance of the WAVE Content Specification?

**Comment by rdoherty0** [comment]
It is accurate that the current market implementations of Dolby Vision use custom NAL units for the carriage of metadata rather than SEI messages, due to the fact that SEI carriage is only recently been published and standardized.  

Dolby is committed that moving forward all implementations of Dolby Vision will decode the metadata regardless of whether it is located in the NAL units or carried in SEI messages.  Since WAVE is a new format, there will be no interoperability issues nor backward compatibility issues.

The profile submission does not make this clear, and for that we apologize and happy to update the submission for clarity if we feel this is necessary to move forward,

**Comment by ZmGorynych** [comment]
It seems that `cdv1` is incompatible with DolbyVision Profile 5 used by Apple: https://developer.apple.com/library/archive/documentation/General/Reference/HLSAuthoringSpec/Requirements.html#//apple_ref/doc/uid/TP40016596-CH2-SW1

**Comment by rdoherty0** [comment]
Per the discussion, this document linked below is the “HLS Authoring Specification for Apple Devices”, currently in use for production of content in the current Apple ecosystem, and this specifies Profile 5 for Dolby Vision content.

For context, the full description and specifications of Dolby Vision profiles/levels and integration into various formats is contained here:
https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-for-creative-professionals.html

Specifically, the profile/levels doc is: https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-profiles-levels.pdf

**Comment by poolec** [comment]
Following those links, if I understand correctly, Profile 5 would not be valid under the HEVC constraints in CMAF because it "uses Dolby Vision-proprietary IPT for color primaries and color matrix" and "uses full range for range".  I think that was the point Kilroy was making on the call.

With that in mind, a Profile 5 media format could not be a Supplemental Data Profile as envisaged for 'cdv1' - it would instead have to be a stand-alone media profile and would have no compatibility back to HDR10 / 'chd1' (which is a CMAF profile and uses BT.2020 color primaries and color matrix and not full_range).

Have I understood correctly?

**Comment by ZmGorynych** [comment]
@poolec yes, seems like this would be a standalone profile. It has a separate codec string (‘dvh1`).

**Comment by rdoherty0** [comment]
@poolec Yes, you are correct -- were we to specify Dolby Vision profile 5 as a media profile in WAVE, it would need to be a different media profile.  It does not use the Supplemental Data mechanism, nor is the content backwards compatible with HDR10.  It would appear as a separate media profile, with a unique 4cc code.

**Comment by johnsim** [comment]
The supplemental data profile ‘cdv1’ is required to meet the “new with WAVE Support” market relevance bar, meaning support from 6 WAVE members, with a minimum of two services and two  device providers.

**Comment by johnsim** [comment]
The supplemental data profile ‘cdv1’ is required to meet the “new with WAVE Support” market relevance bar, meaning support from 6 WAVE members, with a minimum of two services and two  device providers.
