### ISSUE TITLE
CMAF profile 'chdf' needs to be added for 1080p50/60

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/content-specification-task-force#52]
CMAF defines 2 AVC HD profiles;

![image](https://user-images.githubusercontent.com/8490792/178225514-64f2a6c7-b6c6-4758-ad97-5ce8d57a2f78.png)

The WAVE content spec does not include 'chdf' and therefore does not include 1080p50/60. This is common enough that it should be included.

**Comment by johnsim** [comment]
(see [WAVE Content Specification Task Force, Meeting #95 Report | 2022-08-03](https://standards.cta.tech/apps/org/workgroup/cstf/download.php/36613/Notes%20WAVE%20CSTF%20Meeting%2020220803.pdf))

I have added the profile to the Wiki (Media Profile:  [CMAF AVC HD ('chdf')](https://github.com/cta-wave/content-specification-task-force/wiki/Media-Profile:-CMAF-AVC-HD-('chdf'))). 

We require a media profile proponent be designated, but more immediately we need to crowdsource a list of at least 3 digital media services providers and 5 digital media playback devices which support this profile. 

Please respond to this issue with devices and services you are aware of that support this CMAF media profile so that we can fully populate the Wiki entry. After that is complete we will have a follow-on CSTF meeting to discuss approval of this profile for the 2022 edition of the content specification.

**Comment by jpiesing** [comment]
Some manufacturers provide public information about what is supported by their TVs. For example [here](https://developer.samsung.com/smarttv/develop/specifications/media-specifications/2021-tv-video-specifications.html).

TP Vision supports 1080p50 AVC in all of our Philips branded TVs.

1080p50 is confirmed to be used by DVB-T2 services from the German broadcasters [ARD](https://www.ard-digital.de/technik/hdtv/contentblocks/formate-und-bildaufloesung-), [ZDF](https://www-zdf-de.translate.goog/zdfunternehmen/zdf-verbreitungswege-so-empfangen-sie-das-zdf-und-die-sender-100.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc), [RTL](https://www.rtl.de/cms/specials/rtl-hd/empfang.html), [ProSieben](url) and many others on the [Freenet](https://www.dvb-t2hd.de/files/Programmbelegung_DVB-T2_HD_2020.pdf) platform.
Dutch broadcaster NLZiet announced support for 1080p50 [here](https://tweakers-net.translate.goog/nieuws/157210/nlziet-biedt-live-en-replaystreams-aan-op-1080p-met-7-komma-5mbit-s-en-50fps.html?_x_tr_sl=nl&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc).

**Comment by cconcolato** [comment]
My understanding is that `cfhd` is nested in `chdf`, so I'm assuming that you are looking for deployments of content that is `chdf`-compliant but not `cfhd`-compliant, right? This means levels 4.1 and 4.2, right? AFAIK, 4.1 is only allowing higher bitrates compared to 4.0, while 4.2 allows more macroblocks per seconds (https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels). Are you only interested in the max level 4.2 (1080p50/60)?

**Comment by johnsim** [comment]
@cconcolato - sorry I missed your comment. From the meeting notes referenced above:

> • The distinction is in combinations. ‘cfhd’ can provide max frame
height of 1080 and max frame rate of 60fps, but not in
combination. Supporting 1080p/60fps requires ‘chdf’.

So yes - we are interested in content which would require device support for 4.2. @jpiesing has provided a sample list of devices and services. I will arrange a meeting on the topic after IBC.

**Comment by jpiesing** [comment]
Closing as chdf was approved for inclusion in the 2022 WAVE CSTF specification, CTA5001-E.
